services:
  jdk21:
    image: ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}${SEPARATOR_LTS_PREFIX}jdk21-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-21"
        JAVA_VERSION: 21.0.9_10
        WAR_SHA: ${WAR_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        WAR_URL: ${WAR_URL}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}:${JENKINS_VERSION}-jdk21-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}:${JENKINS_VERSION}-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}${SEPARATOR_LTS_PREFIX}${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
  jdk25:
    image: ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}${SEPARATOR_LTS_PREFIX}jdk25-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-25"
        JAVA_VERSION: 25.0.1_8
        WAR_SHA: ${WAR_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        WAR_URL: ${WAR_URL}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}:${JENKINS_VERSION}-jdk25-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}:${JENKINS_VERSION}-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${CONTAINER_NAMESPACE}/${CONTAINER_REPOSITORY}${SEPARATOR_LTS_PREFIX}${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
