services:
  jdk17:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}jdk17-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.16_8
        WAR_SHA: ${WAR_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        WAR_URL: ${WAR_URL}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-jdk17-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
  jdk21:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}jdk21-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-21"
        JAVA_VERSION: 21.0.8_9
        WAR_SHA: ${WAR_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        WAR_URL: ${WAR_URL}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-jdk21-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
