services:
  jdk11:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}jdk11-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.23_9
        JENKINS_SHA: ${JENKINS_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-jdk11-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
  jdk17:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}jdk17-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.11_9
        JENKINS_SHA: ${JENKINS_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-jdk17-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
  jdk21:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}jdk21-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/hotspot/Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        JAVA_HOME: "C:/openjdk-21"
        JAVA_VERSION: 21.0.4_7
        JENKINS_SHA: ${JENKINS_SHA}
        JENKINS_VERSION: ${JENKINS_VERSION}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
        WINDOWS_VERSION: ${WINDOWS_VERSION}
      tags:
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-jdk21-hotspot-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${JENKINS_VERSION}-${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
        - ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}${SEPARATOR_LTS_PREFIX}${WINDOWS_FLAVOR}-${WINDOWS_VERSION}
