FROM raspbian/stretch

# Installing Java
RUN apt-get update
RUN apt-get install oracle-java8-jdk -y
RUN java -version

# Installing Jenkins
RUN apt-get install curl -y
RUN curl -O http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
RUN apt-get remove curl -y
RUN apt-key add jenkins-ci.org.key
RUN sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
RUN sudo apt-get install jenkins -y

CMD ["systemctl", "start", "jenkins"]
