# escape=`
FROM openjdk:8-jdk-windowsservercore-1809

#ARG user=jenkins
#ARG group=jenkins
#ARG uid=1000
#ARG gid=1000
ARG http_port=8080
ARG agent_port=50000
ARG JENKINS_HOME=C:/ProgramData/Jenkins/JenkinsHome

ENV JENKINS_HOME $JENKINS_HOME
ENV JENKINS_SLAVE_AGENT_PORT ${agent_port}

# Jenkins is run with user `jenkins`, uid = 1000
# If you bind mount a volume from the host or a data container,
# ensure you use the same uid
#RUN mkdir -p $JENKINS_HOME \
#  && chown ${uid}:${gid} $JENKINS_HOME \
#  && groupadd -g ${gid} ${group} \
#  && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}
RUN mkdir -p $env:JENKINS_HOME

# Jenkins home directory is a volume, so configuration and build history
# can be persisted and survive image upgrades
VOLUME $JENKINS_HOME

# `C:/ProgramData/Jenkins/Ref/` contains all reference configuration we want
# to set on a fresh new installation. Use it to bundle additional plugins
# or config file with your custom jenkins Docker image.
RUN mkdir -p C:/ProgramData/Jenkins/Ref/init.groovy.d

# jenkins version being bundled in this docker image
ARG JENKINS_VERSION
ENV JENKINS_VERSION ${JENKINS_VERSION:-2.121.1}

# jenkins.war checksum, download will be validated using it
ARG JENKINS_SHA=5bb075b81a3929ceada4e960049e37df5f15a1e3cfc9dc24d749858e70b48919

# Can be used to customize where jenkins.war get downloaded from
ARG JENKINS_URL=https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war

# could use ADD but this one does not check Last-Modified header neither does it allow to control checksum
# see https://github.com/docker/docker/issues/8331
RUN Invoke-WebRequest "$env:JENKINS_URL" -OutFile C:/ProgramData/Jenkins/jenkins.war -UseBasicParsing ;`
    if ((Get-FileHash C:/ProgramData/Jenkins/jenkins.war -Algorithm SHA256).Hash -ne $env:JENKINS_SHA) {exit 1}

ENV JENKINS_UC https://updates.jenkins.io
ENV JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
ENV JENKINS_INCREMENTALS_REPO_MIRROR=https://repo.jenkins-ci.org/incrementals
#RUN chown -R ${user} "$JENKINS_HOME" /usr/share/jenkins/ref

# for main web interface:
EXPOSE ${http_port}

# will be used by attached slave agents:
EXPOSE ${agent_port}

ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log

#USER ${user}

COPY jenkins-support.psm1 C:/ProgramData/Jenkins
COPY jenkins.ps1 C:/ProgramData/Jenkins
ENTRYPOINT ["powershell.exe", "-f", "C:/ProgramData/Jenkins/jenkins.ps1"]

# from a derived Dockerfile, can use `RUN C:/ProgramData/Jenkins/plugin-management-cli.jar -pluginTxtPath active.txt -pluginDirPath C:/ProgramData/Jenkins/Ref/plugins -war C:/ProgramData/Jenkins/jenkins.war` to setup C:/ProgramData/Jenkins/Ref/plugins from a support bundle

ENV PLUGIN_INSTALLATION_TOOL_VERSION 0.1-alpha-2

RUN Invoke-WebRequest -UseBasicParsing -Uri "https://repo.jenkins-ci.org/releases/io/jenkins/plugin-management/plugin-management-cli/$env:PLUGIN_INSTALLATION_TOOL_VERSION/plugin-management-cli-$($env:PLUGIN_INSTALLATION_TOOL_VERSION)-jar-with-dependencies.jar" -OutFile C:/ProgramData/Jenkins/plugin-management-cli.jar ; gci C:/ProgramData/Jenkins
