= Hacking documentation

This document explains how to develop on this repository.

== Requirements

* A Bourne-Again-Shell compatible prompt (bash)
* GNU `make` 3.80+
* Docker with https://github.com/docker/buildx[BuildX] capability
** Docker 20.10+ is recommended as it is usually packaged with Buildx
** Docker 19.03+ is required
** BuildX v0.5.1+ is needed (manual installation of the plugin can be done if you don't have it: https://github.com/docker/buildx)
* https://git-scm.com/[git] 1.6+ (git 2+ is recommended)
* https://stedolan.github.io/jq/[jq] 1.6+
* https://curl.se/[curl] 7+

We recommend https://www.gnu.org/software/parallel/[GNU Parallel] for parallel test execution, but it is not required.

// In case the link breaks, and the bug hasn't been fixed yet:
// On Apple Silicon in native arm64 containers, older versions of libssl in
// debian:buster and ubuntu:20.04 will segfault when connected to some TLS
// servers, for example curl https://dl.yarnpkg.com. The bug is fixed in newer versions
// of libssl in debian:bookworm, ubuntu:21.04 and fedora:35.

Tests currently do not work on Mac M1 due to a link:https://docs.docker.com/docker-for-mac/release-notes/#known-issues[known issue] in 'Docker Desktop 3.4.0'.

== Building

=== Linux

[source,bash]
--
## build all linux platforms
make build

## only build a specific linux image
make build-debian_jdk17 # or build-alpine_jdk17 build-debian_slim_jdk17 build-debian_jdk17 ...

--

== Testing

=== Linux

Tests for Linux images are written using https://github.com/bats-core/bats-core[bats] under the `tests/` directory.

Tests pre-requisites are automatically managed by the `make prepare-test` target (dependency of any `make test*` target)  which:

- Ensures that the `bats` command is installed in the `bats/bin/` directory (along with all the bats project in `./bats/`)
- Ensures that the additional bats helper are installed as git sub-modules in `./tests/test_helper/`

For efficiency, the tests are executed in parallel.

[IMPORTANT]
Due to the parallel execution, each test should be self-contained
and not depend on another test, even inside a given test harness.

Please note that:

- You can disable the parallel execution by setting the environment variable `DISABLE_PARALLEL_TESTS` to the value `true`
- Parallel execution is disabled if the commands `docker` or (GNU) `parallel` are not installed.


You can restrict the execution to only a subset of test harness files. By setting the environment variable `TEST_SUITES`
to the path of the bats test harness file to execute alone.

[source,bash]
--
## Run tests for all linux platforms
make test

## Run tests for a specific linux platform
make test-debian_jdk17 # or test-alpine_jdk17 test-debian_slim_jdk17 test-debian_jdk17 ...

## Run tests for Alpine Linux JDK17 platform in sequential mode
DISABLE_PARALLEL_TESTS=true make test-alpine_jdk17

## Only run the test suite `functions.bats` for the Debian JDK21 platform
TEST_SUITES=./tests/functions.bats make test-debian_jdk21
--

=== Golden files

A golden file (sometimes called a snapshot) is a file that contains the expected output of a program or function.
Tests compare the current output of the code against this "golden" reference to detect regressions or unintended changes.
They are treated as contract artifacts, not test fixtures.

Golden files may be updated only when:

* Output behavior is intentionally changed
* A bug fix corrects previously incorrect output
* A new test case is added

Golden updates must be reviewed like code.

If your work implies golden file changes, those changes must be committed:
* In the same commit as the behavior change
* With a commit message explaining why output changed

Golden updates must never be automatic.

==== How to update a golden file

* Reproduce output manually
* Inspect output
* Update the golden file explicitly
* Run tests

To update a golden file, you can use the dedicated ./tests/update-golden-file.sh helper script.

Example if there are new LTS tags:
[source,bash]
--
./tests/update-golden-file.sh expected_tags_latest_lts make tags LATEST_LTS=true
--

Then ensure corresponding tests are passing with:
[source,bash]
--
bats ./tests/tags.bats
--

== Multiarch support

The buildx tool is used to build our multiarch images, this relies on either QEMU for emulating the architecture being built, or a remote builder configured for the required platform(s).

Planned supported architectures:

* amd64
* arm64
* s390x

== Debugging

In order to debug the controller, use the `-e DEBUG=true -p 5005:5005` when starting the container.
Jenkins will be suspended on the startup in such case,
and then it will be possible to attach a debugger from IDE to it.

== Test the publishing using an overridden target repository on Docker Hub

Create a new dedicated target repository in your Docker Hub account, and use it like follows:

[source,bash]
--
export DOCKERHUB_ORGANISATION=batmat
export DOCKERHUB_REPO=test-jenkins
# The log below will help confirm this override was taken in account:
./publish.sh
Docker repository in Use:
* JENKINS_REPO: batmat/test-jenkins
...
--
