# Hacking documentation

This document explains how to develop on this repository.

## Requirements

The following tools are required:

- A Bourne-Again-Shell compatible prompt
- GNU `make` 3.80+
- Docker with https://github.com/docker/buildx[BuildX] capability
  - Docker 20.10+ is recommended as it is usually packaged with Buildx
  - Docker 19.03+ is required
  - BuildX v0.5.1+ is needed (manual install of the plugin can be done if you don't have it: https://github.com/docker/buildx)
- https://git-scm.com/[git] 1.6+ (git 2+ is recommended)
- https://stedolan.github.io/jq/[jq] 1.5+
- https://curl.se/[curl] 7+

Please note that https://www.gnu.org/software/parallel/[GNU Parallel] is recommended but not required (to allow parallel execution of the tests).

## Building

### Linux

[source,bash]
--
## build all linux platforms
make build

## only build a specific linux platform
make build-debian # or build-alpine build-slim build-jdk11 ...
--

## Testing

### Linux

Tests for Linux images are written using https://github.com/bats-core/bats-core[bats] under the `tests/` directory.

Tests pre-requisites are automatically managed by the `make prepare-test` target (dependency of any `make test*` target)  which:

- Ensures that the `bats` command is installed in the `bats/bin/` directory (along with all the bats project in `./bats/`)
- Ensures that the additional bats helper are installed as git sub-modules in `./tests/test_helper/`

For efficiency, the tests are executed as parallel tasks.

[IMPORTANT]
Due to the parallel execution, each test stanza (e.g. block) should be self-contained
and should not depends on another test stanza, even inside a given test harness.

Please note that:

- You can disable the parallel execution by setting the environment variable `DISABLE_PARALLEL_TESTS` to the value `true`
- Parallel execution is automatically disable if the commands `docker` or (GNU) `parallel` are absent from your system


You can also restrict the execution to only a subset of test harness files by setting the environment variable `TEST_SUITES`
to the path of the bats test harness file to execute alone.

[source,bash]
--
## Run tests for all linux platforms
make test

## Run tests for a specific linux platform
make test-debian # or test-alpine test-slim test-jdk11 ...

## Run tests for Alpine Linux platform in sequential mode
DISABLE_PARALLEL_TESTS=true make test-alpine

## Only run the test suite `functions.bats` for the CentOS 7 platform
TEST_SUITES=./tests/functions.bats make test-centos7
--


## Multiarch support

Multiarch support is added via the `publish-experimental.sh` script, which relies on QEMU for emulating the architecture being built as well as the Docker `https://github.com/estesp/manifest-tool[manifest-tool]` for creating registry
v2.2 "thick" manifests.

When changes are pushed to the upstream Jenkins project, a job is triggered via the `Jenkinsfile` from this repo, which then runs the `publish-experimental.sh` script in parallel mode. Multiarch images created by the script are built/tagged/pushed to the Docker Hub `https://hub.docker.com/r/jenkins4eval/jenkins/[jenkins4eval/jenkins]` repo.

Currently supported architectures:

* amd64
* arm32
* arm64
* s390x
* ppc64le

NOTE:This functionality may change/move at some point in the future.

## Debugging

In order to debug the controller, use the `-e DEBUG=true -p 5005:5005` when starting the container.
Jenkins will be suspended on the startup in such case,
and then it will be possible to attach a debugger from IDE to it.

## Test the publishing using an overridden target repository on Docker Hub

Create a new dedicated target repository in your Docker Hub account, and use it like follows:

[source,bash]
--
export DOCKERHUB_ORGANISATION=batmat
export DOCKERHUB_REPO=test-jenkins
# The log below will help confirm this override was taken in account:
./publish.sh --variant jdk11
Docker repository in Use:
* JENKINS_REPO: batmat/test-jenkins
...
--

## Test the publishing of Multi-arch image using an overridden target repository

Create a new dedicated target repository in your Docker Hub account, and use it like follows:

[source]
--
export DOCKERHUB_ORGANISATION=durgadas
export DOCKERHUB_REPO=jenkins

./publish-experimental.sh --variant alpine

# The log below will help confirm this override was taken in account:
Docker repository in Use:
* JENKINS_REPO: durgadas/jenkins
...
--

Also, one can execute the publish-experimental.sh using:

[source]
--
make publish-experimental
--
