FROM bats-jenkins

COPY plugins.txt C:/ProgramData/Jenkins/Reference/plugins.txt
RUN rm -Force C:/ProgramData/Jenkins/jenkins.war
RUN java -jar C:/ProgramData/Jenkins/plugin-management-cli.jar --plugin-file C:/ProgramData/Jenkins/Reference/plugins.txt

