FROM bats-jenkins

COPY plugins.txt C:/ProgramData/Jenkins/Reference/plugins.txt
RUN Remove-Item -Force C:/ProgramData/Jenkins/jenkins.war
RUN & C:/ProgramData/Jenkins/install-plugins.ps1 -PluginFile C:/ProgramData/Jenkins/Reference/plugins.txt

