FROM bats-jenkins

COPY plugins.txt C:/ProgramData/Jenkins/Ref/plugins.txt
RUN rm -Force C:/ProgramData/Jenkins/jenkins.war
RUN java -jar C:/ProgramData/Jenkins/plugin-management-cli.jar -pluginTxtPath C:/ProgramData/Jenkins/Ref/plugins.txt -pluginDirPath C:/ProgramData/Jenkins/Ref/plugins

