FROM bats-jenkins
# hadolint shell=powershell

COPY plugins.txt C:/ProgramData/Jenkins/Reference/plugins.txt
RUN C:/ProgramData/Jenkins/jenkins-plugin-cli.ps1 --verbose -f C:/ProgramData/Jenkins/Reference/plugins.txt
