FROM bats-jenkins

RUN java -jar C:/ProgramData/Jenkins/plugin-management-cli.jar -plugins maven-plugin:2.7.1 ant:1.3 mesos:0.13.0 git:latest filesystem_scm:experimental docker:1.1.6 -war C:/ProgramData/Jenkins/jenkins.war -pluginDirPath C:/ProgramData/Jenkins/Ref/plugins
