# Note: additional setup is required, see https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

name: Release Drafter

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jenkinsci'
    steps:
      # https://github.com/release-drafter/release-drafter/issues/871#issuecomment-3686135188
      - name: Wait for 15 seconds to ensure GraphQL consistency
        shell: bash
        run: sleep 15s
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Release Drafter
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
