# Note: additional setup is required, see https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

name: Release Drafter

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jenkinsci'
    steps:
      # https://github.com/release-drafter/release-drafter/issues/871#issuecomment-3686135188
      - name: Wait for 15 seconds to ensure GraphQL consistency
        shell: bash
        run: sleep 15s
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Release Drafter
        uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2 # v7.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
